export const productsData = [
    {
        name: 'Blue de Chanel',
        category: 'Designer',
        location: 'Dubai',
        date: '05/28/2024',
        company: 'Paris Parfums Ltd',
        price: "$165",
        totalPrice: '$3560',
        sold: "18",
        status: 'Approved',
        color: "primary",
        image: '/images/bdc.jpg'
    },
    {
        name: 'Baccarat Rouge 540',
        category: 'Designer',
        location: 'Paris',
        date: '04/18/2024',
        company: 'Maison Francis Kurkdjian',
        price: "$325",
        totalPrice: '$4850',
        sold: "11",
        status: 'In Progress',
        color: "warning",
        image: '/images/br5.jpg'
    },
    {
        name: 'Lattafa Khamrah',
        category: 'Arabian',
        location: 'Sharjah',
        date: '07/23/2024',
        company: 'Dubai Fragrance Co.',
        price: "$150",
        totalPrice: '$8376',
        sold: "24",
        status: 'Success',
        color: "success",
        image: '/images/lat.jpg'
    },
    {
        name: 'Creed Aventus',
        category: 'Niche',
        location: 'London',
        date: '12/21/2024',
        company: 'Creed Boutique',
        price: "$435",
        totalPrice: '$9486',
        sold: "9",
        status: 'Rejected',
        color: "danger",
        image: '/images/ca.jpg'
    },
    {
        name: 'Nautica Voyage',
        category: 'Fresh',
        location: 'Houston',
        date: '05/28/2024',
        company: 'Nautica Fragrances',
        price: "$35",
        totalPrice: '$8476',
        sold: "31",
        status: 'Approved',
        color: "primary",
        image: '/images/nt.jpg'
    },
];
